### ISSUE TITLE
Recyclerview does no update

### ISSUE THREAD

**Issue by anbraun** [Ramotion/cardslider-android#22] opened 2018-07-06 09:02 UTC
Using the method notifyDataSetChanged() does not update the recyclerview

**Comment by anbraun** [comment] 2018-07-09 09:20
when will it be merged to master?

**Comment by anbraun** [comment] 2018-07-30 08:07
@dvg4000  , @RamotionDev  ?

**Comment by dvg4000** [comment] 2018-07-30 17:33
It's already merged.

**Comment by YogevUzan** [comment] 2018-09-03 05:51
Nothing works for me too. I tried everything.

**Comment by golovin47** [comment] 2019-02-08 11:42
Hello. In the current version of the lib, cards are getting updated when you set new items to recyclerview's adapter and call notifyDataSetChanged(). If this issue still reproducible, please provide us with source code, which describes how you use this lib.

**Closed as completed by golovin47** 2019-02-08 11:42 UTC
